// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements. See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership. The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing,
//   software distributed under the License is distributed on an
//   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//   KIND, either express or implied. See the License for the
//   specific language governing permissions and limitations
//   under the License.
//
= The Maven Performance Testing
Karl Heinz Marbaise; {docdate}
:author: Karl Heinz Marbaise
:appendix-number:
:sectnums:
:sectlinks:
:xrefstyle: full
:toc: left
//
== Overview
We should try to implement the POM structure based on builder patter to simplify the usage.

The basic idea is to express the structure of a pom file via Java DSL which might look like the following:

[source]
----
CreatePom.of()
.profiles()
  .profile()
  .profile()
.build()
  .defaultGoals("package")
  .plugins(List.of(...))
  .pluginManagement(List.of(..))
.modules(List.of("a"))
----

[source]
----
CreatePom.of()
.build()
  .plugins()
    .plugin().groupId("").artifactId("").version("")
      .executions()
        .execution("id")
          .phase("integration-testing")
          .goals(List.of("XX"))
          .configuration()

  .pluginManagement(List.of(..))
.modules(List.of("a"))
----

How to create the following code in Java:

[source,xml]
.filename.xml
----
<transformers>
  <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
    <manifestEntries>
      <Main-Class>com.soebes.maven.performance.PerformanceSetup</Main-Class>
    </manifestEntries>
  </transformer>
</transformers>
----

[source,java]
----
var pc = PluginConfiguration
  .tag("transformers")
    .tag("transformer", "implementation", "org.apache.maven.plugins.shade.resource.ManifestResourceTransformer")
      .tag("manifestEntries")
      .tag("Main-Class").value("com.soebes.maven.performance.PerformanceSetup")
----

[source]
----
GAV parentGAV = GAV.g("G").a("a").v("v").relativePath("../pom.xml");
GAV parentGAV = GAV.g("G").a("a").v("v");

PluginExecution pe = Execution.id("id")
 .phase("integration-testing")
 .goals(List.of("A","B"))
 .configuration(pc);

Plugin p = Plugin.of("g:a:v")
 .executions(pe);

CreatePom.of("g:a:v")
 .withParent("g:a-p:v")
 .packaging(JAR)
 .build()
   .plugins(p)
 .modules(..)

----

