---
- name: Maven
  hosts: performance
  vars:
    hyperfine: hyperfine-v1.14.0-x86_64-unknown-linux-musl

  tasks:
    - name: Add the user `tmpt`
      ansible.builtin.user:
        name: tmpt
        shell: /bin/bash
        comment: The Maven Performance Testing

    - name: Updated apt packages.
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Installation git tool
      become: yes
      package:
        name: git
        state: present
    - name: Installation zip tool
      become: yes
      package:
        name: zip
        state: present
    - name: Installation unzip tool
      become: yes
      package:
        name: unzip
        state: present
    - name: Installation Zeitsynchronisation
      become: yes
      package:
        name: chrony
        state: present
    - name: Installation wget
      become: yes
      package:
        name: wget
        state: present
    - name: Installation openssl
      become: yes
      package:
        name: openssl
        state: present

    - name: Download SDK Man
      become: yes
      command: 'curl -s "https://get.sdkman.io" -o /home/tmpt/install.sh'
      become_user: tmpt
    - name: Make install.sh exectuable
      command: chmod +x /home/tmpt/install.sh
    - name: Make install.sh owned by tmpt
      command: chown tmpt:tmpt /home/tmpt/install.sh
    - name: Install SDK Man
      ansible.builtin.shell: |
        su -l tmpt install.sh
      args:
        executable: /bin/bash
    - name: Configure SDK Man
      ansible.builtin.template:
        src: templates/config.j2
        dest: /home/tmpt/.sdkman/etc/config
      become_user: tmpt
    - name: Create Maven Cache for user tmpt
      file:
        path: /home/tmpt/.m2/
        state: directory
      become_user: tmpt
    - name: Chown of /home/tmpt/.m2
      command: chown -R tmpt:tmpt /home/tmpt/.m2
    - name: Configure Maven (settings.xml)
      ansible.builtin.template:
        src: templates/settings.xml.j2
        dest: /home/tmpt/.m2/settings.xml
      become_user: tmpt

    - name: Install JDK Versions
      become: yes
      ansible.builtin.shell: |
        source /home/tmpt/.sdkman/bin/sdkman-init.sh
        sdk install java "{{ item }}"
      args:
        executable: /bin/bash
      become_user: tmpt
      loop:
        - 8.0.332-tem
        - 11.0.15-tem
        - 11.0.12-open
        - 17.0.3-tem
        - 18.0.1-tem
        - 19.ea.26-open
        - 8.0.332-sem
        - 11.0.15-sem
        - 17.0.3-sem
        - 18.0.1.1-sem
#         - 8.0.312-sem
#         - 11.0.13-sem
#         - 17.0.1-sem

    # TODO: version etc. make variable with it for easier upgrade.
    - name: Download Hyperfine
      get_url:
        url: 'https://github.com/sharkdp/hyperfine/releases/download/v1.14.0/{{ hyperfine }}.tar.gz'
        dest: /tmp/hyperfine.tar.gz
        checksum: sha256:9d3c53e7da84b41896d4208b722765742af1169a4dab9788321f8597ea159010
    - name: Extract hyperfine.tar.gz into /tmp/
      ansible.builtin.unarchive:
        src: /tmp/hyperfine.tar.gz
        dest: /tmp
        remote_src: true
    - name: Install hyperfine into /usr/local/bin
      ansible.builtin.copy:
        src: '/tmp/{{ hyperfine }}/hyperfine'
        dest: /usr/local/bin/hyperfine
        owner: root
        group: root
        mode: '0755'
        remote_src: yes
    - name: Git clone Testing Project
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/khmarbaise/maven-performance-testing.git'
        dest: /home/tmpt/maven-performance-testing
        update: yes
      become_user: tmpt
    - name: Git clone Apache Maven Project
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/apache/maven.git'
        dest: /home/tmpt/maven
        update: yes
      become_user: tmpt
    - name: Create src/site/markdown directory
      become: true
      ansible.builtin.shell: |
        source /home/tmpt/.sdkman/bin/sdkman-init.sh
        mkdir -p /home/tmpt/maven-performance-testing/src/site/markdown
      args:
        executable: /bin/bash
      become_user: tmpt
