---
- name: Maven
  hosts: maven

  tasks:
    - name: Add the user `tmpt`
      become: true
      ansible.builtin.user:
        name: tmpt
        comment: The Maven Performance Testing
    - name: Installation git tool
      become: true
      package:
        name: git
        state: present
    - name: Installation zip tool
      become: true
      package:
        name: zip
        state: present
    - name: Installation unzip tool
      become: true
      package:
        name: unzip
        state: present
    - name: Installation Zeitsynchronisation
      become: true
      package:
        name: chrony
        state: present
    - name: Download SDK Man
      become: true
      command: 'curl -s "https://get.sdkman.io" -o /home/tmpt/install.sh'
    - name: Make install.sh exectuable
      become: true
      ansible.builtin.file:
        path: /home/tmpt/install.sh
        state: touch
        mode: u+rwx,g+x,o+rx
    - name: Install SDK Man
      command: '/home/tmpt/install.sh'
      become: true
      become_user: tmpt
    - name: Configure SDK Man
      ansible.builtin.template:
        src: templates/config.j2
        dest: /home/tmpt/.sdkman/etc/config
      become: true
      become_user: tmpt
    - name: Create Maven Cache for user tmpt
      become: true
      # TODO: Verwendung Ansible Task
      command: mkdir /home/tmpt/.m2/
      become_user: tmpt

    - name: Configure Maven (settings.xml)
      ansible.builtin.template:
        src: templates/settings.xml.j2
        dest: /home/tmpt/.m2/settings.xml
      become: true
      become_user: tmpt

    - name: Install JDK 8
      become: true
      ansible.builtin.shell: |
        source /home/tmpt/.bashrc
        sdk install java 8.0.302-open
      args:
        executable: /bin/bash
      become_user: tmpt
    - name: Install JDK 11
      become: true
      ansible.builtin.shell: |
        source /home/tmpt/.bashrc
        sdk install java 11.0.12-open
      args:
        executable: /bin/bash
      become_user: tmpt
    - name: Install JDK 17
      become: true
      ansible.builtin.shell: |
        source /home/tmpt/.bashrc
        sdk install java 17.0.1-open
      args:
        executable: /bin/bash
      become_user: tmpt
    # Temporary solution!
    - name: Install Groovy
      become: true
      ansible.builtin.shell: |
        source /home/tmpt/.bashrc
        sdk install groovy 3.0.9
      args:
        executable: /bin/bash
      become_user: tmpt

    # TODO: version etc. make variable with it for easier upgrade.
    - name: Download Hyperfine
      get_url:
        url: https://github.com/sharkdp/hyperfine/releases/download/v1.12.0/hyperfine-v1.12.0-x86_64-unknown-linux-musl.tar.gz
        dest: /tmp/hyperfine.tar.gz
        checksum: sha256:b66e7a55fc1b7fd1f6443861f65bde87a4794c4721dee5e11dc0294f27116efc
    - name: Extract hyperfine.tar.gz into /tmp/
      ansible.builtin.unarchive:
        src: /tmp/hyperfine.tar.gz
        dest: /tmp
        remote_src: true
    - name: Install hyperfine into /usr/local/bin
      become: true
      ansible.builtin.copy:
        src: /tmp/hyperfine-v1.12.0-x86_64-unknown-linux-musl/hyperfine
        dest: /usr/local/bin/hyperfine
        owner: root
        group: root
        mode: '0755'
        remote_src: yes
    - name: Git clone Testing Project
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/khmarbaise/maven-performance-testing.git'
        dest: /home/tmpt/maven-performance-testing
        update: yes
      become_user: tmpt
    - name: Create Testing Project
      become: true
      ansible.builtin.shell: |
        source /home/tmpt/.bashrc
        cd /home/tmpt/maven-performance-testing
        ./generate.groovy
      args:
        executable: /bin/bash
      become_user: tmpt
